### ISSUE TITLE
Bad validation returns ng-model as undefined

### ISSUE THREAD

**Issue by Ehesp** [gkaimakas/angular.validators#1]
Hello,

When the validation returns true (as in, it's failed), the ng-model value is returned as undefined. This causes me issues since it's effectively deleting the value they're attempting to input. Not sure if this is intended or not?

Only tried with is-url though.

**Comment by Ehesp** [comment]
```
<input type="text" ng-model="form.url" is-url>

{{ form.url }}
```

Trying this, if you enter a string which is not a URL, `form.url` is returned as undefined.

**Comment by gkaimakas** [comment]
What you are describing is the way angular handles invalid fields. When a field is invalid the model is not populated at all.

You can ensure that all fields have values by checking the $valid variable of a form.

Example

````
<form name='form' ng-submit='submit(form, data)'>
    <input name='input' ng-model='data' is-url />
</form>
````

and on your controller

````
$scope.submit = function(form, data){
...
    if(form.$valid === true) { //all fields are valid and have values
    //submit your form
    ...
    }
}

Hope this helps.

P.S Thanks for using angular.validators. Hope it makes your work easier
