### ISSUE TITLE
Missing npm release

### ISSUE THREAD

**Issue by himdel** [gkaimakas/angular.validators#7]
There is no 4.4.3 :) https://www.npmjs.com/package/angular.validators?activeTab=versions

Just a reminder @gkaimakas, thanks.
(Or, if you want me to do the npm release...)

**Comment by gkaimakas** [comment]
@himdel hey! Thanks for the reminder.

You should be ok now! 

https://www.npmjs.com/package/angular.validators

**Comment by himdel** [comment]
Thanks! :) Works like a charm :)
